import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const NanumSquareB = localFont({
  src: './fonts/NanumSquareB.ttf',
  variable: '--font-NanumSquareB',
  display: 'swap',
});

const NanumSquareR = localFont({
  src: './fonts/NanumSquareR.ttf',
  variable: '--font-NanumSquareR',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* todo : layout에서 기본폰트를 설정했지만 page에서 적용되지 않는 이슈 */}
      <body
        className={`flex justify-center flex-col items-center w-full ${NanumSquareB.variable} ${NanumSquareR.variable}`}
      >
        <header className="flex w-full h-[60px] bg-white"></header>
        {children}
      </body>
    </html>
  );
}
